don't set app vars and add prod deployment

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -135,8 +135,6 @@ jobs:
         with:
           inlineScript: |
               TAG=$(echo 'https://${{ env.REGISTRY }}/${{ env.EDITOR_IMAGE_NAME }}:${{ github.sha }}' | tr '[:upper:]' '[:lower:]')
-              az webapp config appsettings set --resource-group ${{ secrets.AZURE_WEBAPP_RG }} --name ${{ secrets.EDITOR_AZURE_WEBAPP_NAME }} --settings BRANCH_NAME=${{ github.ref_name }}
-              az webapp config appsettings set --resource-group ${{ secrets.AZURE_WEBAPP_RG }} --name ${{ secrets.EDITOR_AZURE_WEBAPP_NAME }} --settings COMMIT_HASH=${{ github.sha }}
               az webapp config container set --resource-group ${{ secrets.AZURE_WEBAPP_RG }} --name ${{ secrets.EDITOR_AZURE_WEBAPP_NAME }} --docker-custom-image-name $TAG
 
       - name: Deploy Web App to Preview (site)
@@ -144,8 +142,6 @@ jobs:
         with:
           inlineScript: |
               TAG=$(echo 'https://${{ env.REGISTRY }}/${{ env.SITE_IMAGE_NAME }}:${{ github.sha }}' | tr '[:upper:]' '[:lower:]')
-              az webapp config appsettings set --resource-group ${{ secrets.AZURE_WEBAPP_RG }} --name ${{ secrets.SITE_AZURE_WEBAPP_NAME }} --settings BRANCH_NAME=${{ github.ref_name }}
-              az webapp config appsettings set --resource-group ${{ secrets.AZURE_WEBAPP_RG }} --name ${{ secrets.SITE_AZURE_WEBAPP_NAME }} --settings COMMIT_HASH=${{ github.sha }}
               az webapp config container set --resource-group ${{ secrets.AZURE_WEBAPP_RG }} --name ${{ secrets.SITE_AZURE_WEBAPP_NAME }} --docker-custom-image-name $TAG
 
       - name: Check deployed version endpoint
@@ -206,6 +202,8 @@ jobs:
     runs-on: ubuntu-latest
     permissions:
       id-token: write
+    env:
+      API_URL: "https://gordonbeeming.com"
 
     steps:    
       - name: Azure Login
@@ -214,6 +212,13 @@ jobs:
           client-id: ${{ secrets.ARM_CLIENT_ID }}
           tenant-id: ${{ secrets.ARM_TENANT_ID }}
           subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
+
+      - name: Set commit hash
+        id: set-commit-hash
+        shell: bash
+        run: |
+          export COMMIT_HASH=${GITHUB_SHA:0:7}
+          echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_ENV
 
       - name: Deploy Web App to Live (editor)
         uses: Azure/cli@v2
@@ -232,7 +237,45 @@ jobs:
               az webapp config appsettings set --resource-group ${{ secrets.AZURE_WEBAPP_RG }} --name ${{ secrets.SITE_AZURE_WEBAPP_NAME }} --settings BRANCH_NAME=${{ github.ref_name }}
               az webapp config appsettings set --resource-group ${{ secrets.AZURE_WEBAPP_RG }} --name ${{ secrets.SITE_AZURE_WEBAPP_NAME }} --settings COMMIT_HASH=${{ github.sha }}
               az webapp config container set --resource-group ${{ secrets.AZURE_WEBAPP_RG }} --name ${{ secrets.SITE_AZURE_WEBAPP_NAME }} --docker-custom-image-name $TAG
-              
+
+      - name: Check deployed version endpoint
+        shell: pwsh
+        run: |
+          $tries = 0
+          $maxTries = 12
+          $apiDeployed = $false
+          $returnedVersion = ""
+          $expectedCommitHash = $env:COMMIT_HASH
+          $baseUrl = $env:API_URL
+          Write-Host "Waiting for API to deploy at $($baseUrl)/api/DeployVersion"
+          while ($tries -lt $maxTries -and $apiDeployed -eq $false) {
+              $version = Invoke-WebRequest -uri "$($baseUrl)/api/DeployVersion" -Method POST -Body "" -ContentType "application/json"
+              $returnedVersion = $version.Content.Trim('"')
+              if ($version.StatusCode -eq 200 -and $returnedVersion -eq $expectedCommitHash) {
+                  $apiDeployed = $true
+              } else {
+                  Write-Host "Waiting for API to deploy... (try $($tries + 1) of $maxTries)"
+                  Start-Sleep -Seconds 5
+                  $tries++
+              }
+          }
+          if ($apiDeployed -eq $false) {
+              Write-Host "🔥 API did not deploy after $($maxTries * 5) seconds"
+              Write-Host "🔥 Current Version: $($returnedVersion), Expected Version: $($expectedCommitHash)"
+              exit(1)
+          }
+
+          # Write-Host "Health Check at $($baseUrl)/api/HealthCheck"
+          # $response = Invoke-WebRequest -Uri $env:API_URL/api/HealthCheck -Method POST -Body "" -ContentType "application/json"
+          # if ($response.Content -eq "OK") {
+          #   Write-Host "Health check succeeded"
+          # } else {
+          #   Write-Error "Health check failed: $($response.StatusCode)"
+          #   exit 1
+          # }
+        env:
+          COMMIT_HASH: ${{ steps.set-commit-hash.outputs.COMMIT_HASH }}
+
       - name: Azure Logout
         uses: azure/CLI@v2
         with:
